#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 31 17:34:06 2018

@author: tiffanyensor
"""

########
SQL_password = 'password'
#######


#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# IMPORTS
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import psycopg2

from collections import Counter

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from mpl_toolkits.basemap import Basemap
import gmplot

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# SQL FUNCTIONS
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------


def postgres_query(string_command, password=SQL_password):
    # takes in PostgreSQL command as text, outputs dataframe
    conn = psycopg2.connect(host="localhost",database="Yelp", user="postgres", password=password)
    cur = conn.cursor()
    cur.execute(string_command)
    conn.commit()
    rows = cur.fetchall()
    colnames = [desc[0] for desc in cur.description]
    cur.close()
    conn.close()
    rows =  [list(i) for i in rows]
    rows = pd.DataFrame(rows, columns=colnames)
    return rows

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# 2. Top 10 restaurants in Toronto with highest popularity. You are free to
# define your ‘popularity’, as long as it makes sense.
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------

# A popular restaurant should be: open, 

# Get open restaurants in Toronto and order by number of positive reviews
# where positive review >= 4
data = postgres_query("""SELECT business.name, COUNT(*) AS n_pos_rev FROM business
                      JOIN reviews on reviews.business_id = business.business_id
                      WHERE reviews.stars >= 4
                      AND business.city LIKE 'Toronto'
                      AND business.is_open = 1
                      AND business.categories LIKE '%Restaurant%'
                      GROUP BY business.name
                      ORDER BY COUNT(*) DESC;
                      """)


# Plot top 10 restaurants: name vs number of positive rating
# show avg rating somehow?
# in the last year?
plt.figure(1, figsize = (5,8))
plt.gca().invert_yaxis()
plt.barh(data.name[:10], data.n_pos_rev[:10])
plt.title("Top 10 Popular Restaurants in Toronto")
plt.xlabel("Number of Positive Reviews")
plt.savefig("PopularTorontoRestaurants.pdf", bbox_inches="tight")
plt.show()

# Top 10: let's say they need a 4 or 5 star rating
top_10_list = []
counter = 0
i = 0

while counter < 10:
    if data.stars[i] >= 4.0:
        top_10_list.append(data.name[i])
        counter += 1
    i += 1


print("The top 10 most popular Toronto restaurants are: ")
for i, val in enumerate(top_10_list):
    print(i+1,". ",val)

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# 3. How many Canadian residents reviewed the business “Mon Ami Gabi” in last 1 year?
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------

# Get users who reviewed "Mon Ami Gabi" in the last year:
MAG_reviewers_this_year = postgres_query("""SELECT reviews.uder_id, business.name, reviews.review_date 
                                         FROM reviews
                                         JOIN business ON reviews.business_id = business.business_id
                                         WHERE reviews.review_date > (current_date - interval '1 year') 
                                         AND business.name = 'Mon Ami Gabi';
                                         """)

# The problem here is finding out which reviewers are Canadian, since reviewers
# addresses are not known.

# The country where each reviewer has reviewed the most restaurants is 
# probably their home country.


    

    
# number of revies by each user:
# SELECT count(*) FROM reviews GROUP BY uder_id LIMIT 10;
"""
SELECT uder_id FROM reviews
JOIN business on business.business_id = reviews.business_id
GROUP BY uder_id 
LIMIT 10;
"""



"""
SELECT business.name, reviews.review_text, reviews.review_date FROM reviews
JOIN business ON reviews.business_id = business.business_id
WHERE reviews.review_date > (current_date - interval '1 year') 
AND business.name = 'Mon Ami Gabi'
ORDER BY reviews.review_date
LIMIT 100;
"""


#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# 4. Top 10 most common words in the reviews of the business “Chipotle Mexican Grill”
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------

# Select all "Chipotle Mexican Grill" reviews from the SQL database
data = postgres_query(" SELECT business.name, reviews.review_text FROM reviews JOIN business ON business.business_id = reviews.business_id WHERE business.name LIKE 'Chipotle Mexican Grill';")

# Simple tokenizer function
def simple_tokenizer(review):
    review = review.lower()                        # convert to lowercase
    tokens = review.split()                        # split into words
    tokens = [t for t in tokens if t.isalpha()]    # remove non-alpha characters
    return tokens


# Get a list of tokenized words
tokenized_words =[]

for rev in data["review_text"]:
    tokens = simple_tokenizer(rev)
    for word in tokens:
        tokenized_words.append(word)
    

# Count occurance of each word in tokenized_words and order by frequency
word_count = Counter(tokenized_words).most_common()
top_10_chipotle_words = [word[0] for word in word_count[:10]]

print("The top 10 most frequent words in the Chipotle reviews are :")
for index, word in enumerate(top_10_chipotle_words):
    print(index+1,". ",word)

# from an analytics point of view, this is not very helpful.
# we should remove stopwords, lemmatize, and stem to get a better idea of the
# important words

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

# Tokenizer function
def better_tokenizer(review):
    tokens = simple_tokenizer(review)
    tokens = [lemmatizer.lemmatize(t) for t in tokens]      # lemmatize
    tokens = [t for t in tokens if len(t) > 2]              # remove short words
    tokens = [t for t in tokens if t not in stop_words]     # remove stopwords
    return tokens

new_tokenized_words =[]

for rev in data["review_text"]:
    tokens = better_tokenizer(rev)
    for word in tokens:
        new_tokenized_words.append(word)


# Count occurance of each word in tokenized_words and order by frequency
word_count = Counter(new_tokenized_words).most_common()
top_10_chipotle_words = [word[0] for word in word_count[:10]]

print("The top 10 most frequent USEFUL words in the Chipotle reviews are :")
for index, word in enumerate(top_10_chipotle_words):
    print(index+1,". ",word)




#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# 6. What’s the percentage of users, who reviewed “Mon Ami Gabi”, and also
# reviewed at least 10 other restaurants located in Ontario?
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------

# Get users who reviewed "Mon Ami Gabi"
MonAmiGabi_reviewers = postgres_query("""
                           SELECT reviews.uder_id, reviews.business_id, business.name 
                           FROM reviews 
                           JOIN business on reviews.business_id = business.business_id 
                           WHERE business.name LIKE 'Mon Ami Gabi';
                           """)
    
    
# Get review counts > 10 for each user for restaurants in Ontario
Ontario_reviews = postgres_query("""SELECT reviews.uder_id, COUNT(*) from reviews
                                 JOIN users ON users.user_id = reviews.uder_id
                                 JOIN business ON business.business_id = reviews.business_id
                                 WHERE business.state_province LIKE 'ON'
                                 GROUP BY reviews.uder_id
                                 HAVING COUNT(*) >= 10
                                 """)

# Number of users who reviewed "Mon Ami Gabi"
n_MonAmiGabi_reviewers = MonAmiGabi_reviewers["uder_id"].count()

# Total number of reviewers
n_reviewers = postgres_query("SELECT COUNT(*) FROM reviews").values
n_reviewers = n_reviewers[0][0]

# Number of users who reviewed "Mon Ami Gabi" and at least 10 other restaurants in Ontario
counter = 0

for user in Ontario_reviews["uder_id"]:
    if user in MonAmiGabi_reviewers["uder_id"].values:
        counter = counter + 1

# Calculate percent of MonAmiGabi reviewers that reviewed at least 10 ON restaurants
percent_of_MonAmiGabi = counter/n_MonAmiGabi_reviewers

percent_of_total = (counter*100.00/n_reviewers)

print(round(percent_of_total,4),"% of reviewers reviewed both Mon Ami Gabi and at least 10 Ontario restaurants.")



#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# EXTRA ANALYSIS: Plot the bakeries in Toronto on a map to see underserviced areas
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------

bakeries = postgres_query("""SELECT name, latitude, longitude, categories
                          FROM business
                          WHERE city LIKE 'Toronto'
                          AND categories LIKE '%Bakeries%';""")

# Use Basemap to plot a map of Toronto with bakery locations identified

gmap1 = gmplot.GoogleMapPlotter(43.7, -79.39, 13)
gmap1.scatter(bakeries["latitude"], bakeries["longitude"])
gmap1.draw('map.html')


plt.figure(figsize=(10,8))








plt.savefig('bakery_map.pdf')




plt.figure(figsize = (8,6))
plt.scatter(bakeries["latitude"], bakeries["longitude"])
#plt.xlim(43.6, 43.84)
#plt.ylim(-79.5, -79.2)
plt.show()


#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# EXTRA: The most popular restaurant in Toronto is Pai Northern Thai
# Kitchen. How have their reviews changed over the years?
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------

def ratings_by_year(business_name):
    
    # replace SQL escape character
    business_name = business_name.replace("'", "''")
    
    bus_data = postgres_query("""SELECT extract(year from reviews.review_date) as review_year, reviews.stars, COUNT(*)
                          FROM reviews
                          JOIN business ON reviews.business_id = business.business_id
                          WHERE business.name LIKE '"""+business_name+"""'
                          GROUP BY review_year, reviews.stars;
                          """)
    
    if bus_data.empty:
        print('There is no information on the business "'+business_name+'".')
        return -1;
    
    bus_data = bus_data.fillna(0)
    bus_data = bus_data.astype(int)

    bus_data = bus_data.pivot(index="review_year", columns="stars", values="count")
    years = bus_data.index
    
    # Set up plot area, leving room on the right for the legend
#    fig = plt.figure()
    ax = plt.subplot(111)
    box = ax.get_position()
    ax.set_position([box.x0, box.y0, box.width * 0.8, box.height])

    # Stacked bar plots
    p1=plt.bar(years, bus_data[1], color='red')
    p2=plt.bar(years, bus_data[2], bottom=bus_data[1], color='gold')
    p3=plt.bar(years, bus_data[3], bottom=bus_data[1]+bus_data[2], color='yellow')
    p4=plt.bar(years, bus_data[4], bottom=bus_data[1]+bus_data[2]+bus_data[3], color='palegreen')
    p5=plt.bar(years, bus_data[5], bottom=bus_data[1]+bus_data[2]+bus_data[3]+bus_data[4], color='mediumseagreen')

    # Plot specifications
    ax.legend((p1, p2, p3, p4, p5), ('1 Star', '2 Star', '3 Star', '4 Star', '5 Star'), loc = "upper left", bbox_to_anchor = (1, 1))
    plt.title(business_name+" Ratings by Year")
    plt.xlabel("Year")
    plt.ylabel("Number of Reviews")
    plt.savefig(business_name+"_Ratings_By_Year.pdf", bbox_inches="tight")
    plt.show()

# Try this out for a few restaurants
ratings_by_year("Pai Northern Thai Kitchen")
ratings_by_year("McDonalds")
ratings_by_year("Subway")
ratings_by_year("Mon Ami Gabi")
ratings_by_year("Starbucks")
ratings_by_year("ARIA Resort & Casino")

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
